#!/usr/bin/env python3

import argparse
import sys
from collections import defaultdict


def main():
    parser = argparse.ArgumentParser(description='Count match and mismatch in matched bed file')
    parser.add_argument('BED', type=argparse.FileType('r'), help='Matched BED file generated by match_analysis.py')
    parser.add_argument('-o', default=sys.stdout, type=argparse.FileType('w'), help='Output basename')
    args = parser.parse_args()

    # initialization
    data = [[0] * 4 for _ in range(4)]
    order = {'A':0, 'C':1, 'G':2, 'T':3}

    # deal with each bed file
    for l in args.BED:
        ws = l.rstrip().split('\t')
        if ws[3] not in order or ws[4] not in order:
            continue
        data[order[ws[3]]][order[ws[4]]] += 1

    # output
    args.o.write('ARS_in_reads\tA\tC\tG\tT\n')
    for k, v in order.items():
        args.o.write(f'{k}\t' + '\t'.join([str(x) for x in data[v]]) + '\n')

    print('Done!')

if __name__ == '__main__':
    main()
